version: '3'
services:
  storage:
    image: busybox
    volumes:
      - /var/lib/mysql
  mysql:
    image: mysql:5.7
    volumes:
      - storage:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
  node:
    image: node:9-alpine
    user: node
    volumes:
      - .:/var/opt/app
    working_dir: /var/opt/app
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "3"
    entrypoint: sh -c
    command: |
      "npm install && \
      npm run watch"
  python:
    image: h3poteto/python:3.6.4
    links:
      - node:node
      - mysql:mysql
    ports:
      - "8000:8000"
    volumes:
      - .:/var/opt/app
    working_dir: /var/opt/app
    command: /bin/bash

volumes:
  storage:
