version: 2
jobs:
  build:
    docker:
      - image: node:9-alpine
    working_directory: /var/opt/app
    steps:
      - checkout
      - run:
          name: Check node version
          command: |
            node --version
            npm --version
      # キャッシュはS3に置いてあるがそれらのやり取り時に証明書が必要になる
      # 自己証明書を生み出すためのca-certificatesがないと通信できない
      - run:
          name: Install ca-certificate
          command: apk add --no-cache ca-certificates
      - restore_cache:
          name: Restoring cache - node_modules
          keys:
            - node_modules-{{ arch }}-{{ checksum "package.json" }}-{{ checksum "package-lock.json" }}
      - run:
          name: Node packages install
          command: npm install
      - run:
          name: Build manifest file
          command: npm run compile
      - save_cache:
          name: Saving cache - node_modules
          key: node_modules-{{ arch }}-{{ checksum "package.json" }}-{{ checksum "package-lock.json" }}
          paths:
            - "node_modules"

  image:
    machine: true
    steps:
      - checkout
      - run:
          name: Check docker version
          command: docker version
      - run:
          name: Docker build
          command: |
            docker build -t $AWS_ECR_REPOSITORY:$CIRCLE_SHA1 .
            docker tag $AWS_ECR_REPOSITORY:$CIRCLE_SHA1 $AWS_ECR_REPOSITORY:latest
      - run:
          name: Docker push
          command: |
            $(aws ecr get-login --no-include-email --region ap-northeast-1)
            docker push $AWS_ECR_REPOSITORY:$CIRCLE_SHA1
            docker push $AWS_ECR_REPOSITORY:latest

  deploy:
    docker:
      - image: h3poteto/kubectl:latest
        environment:
          CLUSTER_NAME: external-prd.cluster.k8s.local
    working_directory: /var/opt/kube
    steps:
      - run:
          name: entrypoint
          command: |
            /var/opt/kube/entrypoint.sh
      - run:
          name: install kube-job
          command: |
            wget https://github.com/h3poteto/kube-job/releases/download/v0.1.1/kube-job_0.1.1_linux_amd64.zip
            unzip kube-job_0.1.1_linux_amd64.zip
            ./kube-job version
      - run:
          name: Clone k8s services
          command: |
            git clone https://github.com/h3poteto/k8s-services.git
      - run:
          name: Version
          command: |
            kubectl version
      - run:
          name: migration
          command: |
            ./kube-job run --config=$HOME/.kube/config --template-file=k8s-services/external-prd/masudastream/job.yml --args="python manage.py migrate" --container="django"
      - run:
          name: deploy
          command: |
            kubectl patch -f k8s-services/external-prd/masudastream/deployment.yml -p "{\"spec\":{\"template\":{\"spec\":{\"containers\":[{\"name\":\"django\",\"image\":\"${AWS_ECR_REPOSITORY}:${CIRCLE_SHA1}\"}]}}}}"


workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - image:
          filters:
            branches:
              only:
                - master
      - deploy:
          filters:
            branches:
              only:
                - master
          requires:
            - image
            - build
